[build]
command = "npm run build"
publish = "dist"
node_version = "20.x"

[build.environment]
NODE_VERSION = "20"
NPM_VERSION = "9"

[[headers]]
for = "/*"
  [headers.values]
  X-Frame-Options = "DENY"
  X-Content-Type-Options = "nosniff"
