[build]
command = "npm run build"
publish = "dist"
pages_build_output_dir = "dist"
node_version = "20.x"

[build.environment]
NODE_VERSION = "20"
NPM_VERSION = "9"
VITE_APP_TITLE = "iHelper Resource Library"
VITE_APP_DESCRIPTION = "Practical business solutions for entrepreneurs"

[[headers]]
for = "/*"
  [headers.values]
  X-Frame-Options = "DENY"
  X-Content-Type-Options = "nosniff"
  Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
  Referrer-Policy = "strict-origin-when-cross-origin"
  Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' https://cdn.jsdelivr.net; style-src 'self' 'unsafe-inline' https://cdn.jsdelivr.net"

[context.production.environment]
VITE_ENVIRONMENT = "production"

[context.deploy-preview.environment]
VITE_ENVIRONMENT = "staging"

[[redirects]]
from = "/resources/*"
to = "/index.html"
status = 200

[[headers]]
for = "/assets/*"
  [headers.values]
  Cache-Control = "public, max-age=31536000, immutable"

[performance]
  [[performance.caching]]
  path = "/*"
  strategy = "cache-first"
  ttl = 3600

[seo]
site_name = "iHelper Resource Library"
keywords = ["business resources", "workflow automation", "digital marketing", "professional development"]
