[build]
command = "npm run build"
publish = "dist"
node_version = "20.x"

[build.environment]
NODE_VERSION = "20"
NPM_VERSION = "9"
VITE_APP_TITLE = "iHelper Resource Library"
VITE_APP_DESCRIPTION = "Practical business solutions for entrepreneurs"

[[headers]]
for = "/*"
  [headers.values]
  X-Frame-Options = "DENY"
  X-Content-Type-Options = "nosniff"
  Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
  Referrer-Policy = "strict-origin-when-cross-origin"
  Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' https://cdn.jsdelivr.net; style-src 'self' 'unsafe-inline' https://cdn.jsdelivr.net"

[context.production.environment]
VITE_ENVIRONMENT = "production"

[context.deploy-preview.environment]
VITE_ENVIRONMENT = "staging"

[[redirects]]
from = "/resources/*"
to = "/index.html"
status = 200

[[headers]]
for = "/assets/*"
  [headers.values]
  Cache-Control = "public, max-age=31536000, immutable"

[performance]
  [[performance.caching]]
  path = "/*"
  strategy = "cache-first"
  ttl = 3600

[deployment]
version = "1.0.0"
date = "2024-12-24"

[site_config]
name = "iHelper Comprehensive Resource Library"
domain = "www.ihelper.com"

[performance]
caching_strategy = "aggressive"
minification = true
brotli_compression = true

[security]
ssl = "full"
always_use_https = true
browser_integrity_check = true

[seo]
site_name = "iHelper Resource Library"
keywords = ["business resources", "workflow automation", "digital marketing", "professional development"]
indexing = true
crawl_delay = 10

[directories]
developed = [
    "13_Online_Courses",
    "14_Ebook_Summaries", 
    "15_Professional_Templates"
]

[optimization]
html_optimization = true
css_optimization = true
javascript_optimization = true

[accessibility]
wcag_compliance = "AA"
color_contrast_ratio = "4.5:1"

[monitoring]
error_tracking = true
performance_logging = true

[cache_rules]
static_assets_cache_time = "1y"
dynamic_content_cache_time = "1h"
