[pages]
project_name = "ihelper-resource-library"
account_id = ""  # To be filled with actual Cloudflare account ID
compatibility_date = "2024-12-24"

[build]
command = "npm run build"
publish_directory = "dist"
